-- 코드를 입력하세요
# 22.10.16 대여 중인 자동차는 '대여중'/아닌 자동차는 '대여 가능'을 표시하는 칼럼(AVAILABILITY) 추가


# SELECT C.CAR_ID, IF(C.CAR_ID  IN (RENTALED.CAR_ID), '대여 중', '대여 가능') AS AVAILABILITY
# FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY C, (SELECT CAR_ID
#                                     FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
#                                     WHERE START_DATE<=DATE('2022-10-16') AND DATE('2022-10-16')<END_DATE
# ) RENTALED
# GROUP BY C.CAR_ID
# ORDER BY C.CAR_ID DESC;                                    

# SELECT CAR_ID, START_DATE, END_DATE
# FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
# # WHERE DATE('2022-10-16') BETWEEN START_DATE AND END_DATE 
# WHERE START_DATE <= DATE('2022-10-16') < END_DATE 
# GROUP BY CAR_ID
# ORDER BY CAR_ID DESC;    


# SELECT C.CAR_IDIF(C.CAR_ID=RC.CAR_ID, '대여 중', '대여 가능') AS AV
# FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY C, (SELECT CAR_ID
#     FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
#     WHERE START_DATE<=DATE('2022-10-16') AND DATE('2022-10-16')<END_DATE ) RC
# # WHERE C.CAR_ID=RC.CAR_ID
# GROUP BY C.CAR_ID
# ORDER BY C.CAR_ID DESC;    

# SELECT IF(C.CAR_ID = DC.CAR_ID, '대여 중', '대여 가능') AS AV
# FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY C, (SELECT CAR_ID
#     FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
#     WHERE START_DATE<=DATE('2022-10-16') AND DATE('2022-10-16')<END_DATE) DC
# GROUP BY C.CAR_ID
# ORDER BY C.CAR_ID DESC;    

SELECT C.CAR_ID, IF(SUM(IF(C.CAR_ID = DC.CAR_ID, 1, 0)>=1), '대여중', '대여 가능') AS AVAILABILITY
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY C, (SELECT CAR_ID
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
    WHERE START_DATE<=DATE('2022-10-16') AND DATE('2022-10-16')<=END_DATE) DC
GROUP BY C.CAR_ID
ORDER BY C.CAR_ID DESC;



